---
  title: "Schedule"
---
  
  **Click on the text like "Week 1: Sep 02 -- Sep 06" to expand or collapse the items we covered in that week.**
  
  I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
      sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Sep 02 -- Sep 06", "

#### Wed, Sep 04
 * **In class**, we will work on:
    * Overview of course (slides): [pdf](materials/20190904_intro/20190904_slides_class_overview.pdf)
    * Warmup activity in groups: [pdf](materials/20190904_intro/20190904_slr_warmup.pdf)
    * Brief reminder of commands for simple linear regression in R: [pdf](materials/20190904_intro/20190904_SLR_summary.pdf)
    * Matrix notation for multiple regression (See Chapter 1 of ISLR and [https://en.wikipedia.org/wiki/Linear_regression#Introduction](https://en.wikipedia.org/wiki/Linear_regression#Introduction))
        * Lecture notes: [pdf](materials/20190904_intro/20190904_lecture_notes.pdf)
        * R code example: [Rmd](materials/20190904_intro/20190904_beer_example.Rmd)
    * Get set up with GitHub:
        * Video overview: [https://www.youtube.com/watch?v=YxZ8J2rqhEM](https://www.youtube.com/watch?v=YxZ8J2rqhEM)
        * pdf with detailed instructions: [pdf](materials/20190904_intro/Stat340-github-setup.pdf)
        * On step 1, please enter your name and GitHub user name in this form: [https://forms.gle/tmv25zoB4EPipa7f8](https://forms.gle/tmv25zoB4EPipa7f8)
 * **After class**, please:
    * Sign up for our class on Piazza: https://piazza.com/mtholyoke/fall2019/stat340
    * Fill out this poll about when my office hours should be held: [http://whenisgood.net/8jeinxd](http://whenisgood.net/8jeinxd)
    * Finish getting RStudio set up with GitHub if you didn't get there in class - ask if you have any questions!
    * Review the handout about simple linear regression
    * Start reading Chapter 1, and Sections 2.1, 2.2.1, 2.2.2, 3.1, 3.2, and 3.3 of ISLR.  This material should be mostly familiar, but we will discuss this material over the first two weeks or so of class.
    * Ask any questions on piazza!

#### Fri, Sep 06
 * **In class**, we will work on:
    * Polynomial Regression (Section 3.3 of ISLR): [pdf](materials/20190906_polynomial_train_test/20190906_polynomial_regression.pdf)
    * Motivate model selection by minimizing Residual Sum of Squares (Section 3.1 of ISLR): [pdf](materials/20190906_polynomial_train_test/20190906_train_test_Example_1.pdf)
 * **After class**, please:
    * Continue reading Chapter 1, and Sections 2.1, 2.2.1, 2.2.2, 3.1, 3.2, and 3.3 of ISLR.
    * Start on Homework 1, due Friday Sep 13; assigned on GitHub.
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Sep 09 -- Sep 13", "
#### Mon, Sep 09
 * **In class**, we will work on:
    * Multiple regression in matrix notation: [pdf](materials/20190909_matrix_least_squares/20180909_matrix_formulation_multiple_reg.pdf)
    * Model estimation by minimizing Residual Sum of Squares (Sections 3.1.1 and 3.2.1 of ISLR)
        * Lecture notes: [pdf](materials/20190909_matrix_least_squares/lm_estimation.pdf). Note that our derivation in terms of matrices is not discussed in our text book. :(
 * **After class**, please:
    * Continue reading Chapter 1, and Sections 2.1, 2.2.1, 2.2.2, 3.1, 3.2, and 3.3 of ISLR.


#### Wed, Sep 11
 * **In class**, we will work on:
    * Finish second example from last class.
    * Review of orthogonal projections
        * Lecture notes: [pdf](materials/20190909_matrix_least_squares/projections_review.pdf)
    * Matrix/linear algebra view of fitted values
        * $H = X (X'X)^{-1} X'$ is the hat matrix.
        * $\\hat{y} = X \\hat{\\beta} = Hy$ is the orthogonal projection of y into the column space of $X$.
        * ANOVA Example: [html](materials/20190909_matrix_least_squares/anova_proj.html)
 * **After class**, please:
    * Work on HW1, due Friday Sep 13

#### Fri, Sep 13
 * **In class**, we will work on:
    * R commands for doing matrix operations [.R](materials/20190913_more_matrices/R_matrix_commands.R)
    * What it means for X to not have full column rank
        * Handout: [pdf](materials/20190913_more_matrices/20180913_X_rank.pdf)
        * Interactive plots for first example: [html](materials/20190913_more_matrices/RSS_badness.html)
    * If time, start a worksheet that will be part of your next homework assignment: [pdf](materials/20190913_more_matrices/20180913_in_class_hw_example.pdf)
 * **After class**, please:
    * Do HW2, due Friday Sep 20, to be assigned on GitHub some time Saturday
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Sep 16 -- Sep 20", "
#### Mon, Sep 16
 * **In class**, we will work on:
    * Train/test splits:
        * Motivating example: [pdf](materials/20190916_polynomial_train_test/20190916_train_test_Example.pdf)
        * Example wrap up: [pdf](materials/20190916_polynomial_train_test/20190916_train_test_Example_wrapup.pdf)
    * Lab 01, about train/test splits
 * **After class**, please:
    * Read Sections 5.1.1 through 5.1.4 of ISLR
    * Work on HW2, due Friday Sep 20

#### Wed, Sep 18
 * **In class**, we will work on:
    * For loops in R: [pdf](materials/20190918_for_loops_crossvalidation/for_loops.pdf)
    * Cross-validation: [pdf](materials/20190918_for_loops_crossvalidation/20190918_crossvalidation.pdf)
    * Time for Lab 1 (individual GitHub repositories) and Lab 2 (https://github.com/mhc-stat340-f2019-sec01/Lab02)
 * **After class**, please:
    * Work on HW2, due Friday Sep 20

#### Fri, Sep 20
 * **In class**, we will work on:
    * Pairs Plots: [pdf](materials/20190920_paris_plots/20190920_Pairs_Plots.pdf)
    * Work on labs
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", TRUE, "Week 4: Sep 23 -- Sep 27", "
#### Mon, Sep 23
 * **In class**, we will work on:
    * Expected test set MSE and the Bias/Variance trade-off.
        * Slides: [pdf](materials/20190923_mse_bias_var/Bias_Variance_Trade_Off.pdf)
        * Source for Slides: [Rmd](materials/20190923_mse_bias_var/20190923_slides_mse_bias_var.Rmd)
 * **After class**, please:
    * Finish Lab 2
    * Study for quiz on Wed


#### Wed, Sep 25
 * **In class**, we will work on:
    * Quiz
    * Review Lab 2.  My answers are posted at https://github.com/mhc-stat340-f2019-sec01/Lab02
    * QQ Plots: [pdf](materials/20190925_transformations/20180917_QQ.pdf)
 * **After class**, please:


#### Fri, Sep 27
 * **In class**, we will work on:
    * Transformations: [pdf](materials/20190925_transformations/20180917_Transformations.pdf)
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", TRUE, "Week 5: Sep 30 -- Oct 04", "
#### Mon, Sep 30
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Oct 02
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Oct 04
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", TRUE, "Week 6: Oct 07 -- Oct 11", "
#### Mon, Oct 07
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Oct 09
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Oct 11
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", TRUE, "Week 7: Oct 14 -- Oct 18", "
#### Mon, Oct 14
 * **No Class**: Midsemester Break.  Safe travels!


#### Wed, Oct 16
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Oct 18
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", TRUE, "Week 8: Oct 21 -- Oct 25", "
#### Mon, Oct 21
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Oct 23
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Oct 25
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", TRUE, "Week 9: Oct 28 -- Nov 01", "
#### Mon, Oct 28
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Oct 30
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Nov 01
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", TRUE, "Week 10: Nov 04 -- Nov 08", "
#### Mon, Nov 04
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Nov 06
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Nov 08
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", TRUE, "Week 11: Nov 11 -- Nov 15", "
#### Mon, Nov 11
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Nov 13
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Nov 15
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", TRUE, "Week 12: Nov 18 -- Nov 22", "
#### Mon, Nov 18
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Nov 20
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Nov 22
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", TRUE, "Week 13: Nov 25 -- Nov 29", "
#### Mon, Nov 25
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Nov 27
 * **No Class**: Thanksgiving Break.  Safe travels!


#### Fri, Nov 29
 * **No Class**: Thanksgiving Break.  Safe travels!
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", TRUE, "Week 14: Dec 02 -- Dec 06", "
#### Mon, Dec 02
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Dec 04
 * **In class**, we will work on:
    * **Evan is away at a conference.**
    * Time to work on your projects in groups.
 * **After class**, please:


#### Fri, Dec 06
 * **In class**, we will work on:
    * **Evan is away at a conference.**
    * Time to work on your projects in groups.
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", TRUE, "Week 15: Dec 09 -- Dec 13", "
#### Mon, Dec 09
 * **In class**, we will work on:
 * **After class**, please:


")
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: Dec 16 -- Dec 20", "We will not have a final exam in this class.")
```

